### ISSUE TITLE
Add example screenshots of the TUI to the README

### ISSUE THREAD

**Issue by ccgarant** [blinklabs-io/nview#131]
I think an nview TUI screenshot at the top of the README and maybe a few more examples at the end would really help give a quick visual, be pretty convincing and motivating for running nview. It's really an awesome TUI I think it would really be a big benefit.

**Comment by wolf31o2** [comment]
I will definitely do this once I finish the UI rewrite. It'll give it a more unique look and also update the functionality a bit.
