### ISSUE TITLE
Filter peers to TCP

### ISSUE THREAD

**Issue by wcatz** [blinklabs-io/nview#162]
P view is displaying my routers DNS server(UDP) on 53 as a peer of cardano-node. It was also picking up the Samba connection(TCP) on 445 on my router that I was mounting in fstab in the node host.

**Comment by wolf31o2** [comment]
I dug a bit and `process.ConnectionsWithContext` will use "all" when getting connections. The ticket switches this to "tcp" to limit it to tcp4 and tcp6 connections.
