### ISSUE TITLE
Peer Analysis disabled on FreeBSD - gopsutil lacks ConnectionsWithContext implementation

### ISSUE THREAD

**Issue by reqlez** [blinklabs-io/nview#40]
As per this line here: 
https://github.com/shirou/gopsutil/blob/03ae19bea8ddab95f5f373d14f9f7a91ebc293b2/process/process_freebsd.go#L290

**Comment by wolf31o2** [comment]
I filed shirou/gopsutil#1551 to use `lsof` (same as Darwin) when present
